#!/usr/bin/env bash

# This file needs lots of refactoring

if [ -z "$PS1" ]; then
  echo -e "${COLOR_RED}You should source this, not run it, for example: source link${COLOR_NC}\n\n"
fi

rm ~/.bash_profile
rm ~/.bashrc
rm ~/.bashrc_help
rm ~/.bashrc_app_specific
rm ~/.bashrc_host_aliases
#rm ~/.bashrc_deploy
rm ~/.railsrc
#rm ~/.bashrc_gilt

ln -s ~/Dropbox/dotfiles/etc/bash_profile ~/.bash_profile
ln -s ~/Dropbox/dotfiles/etc/bashrc ~/.bashrc
ln -s ~/Dropbox/dotfiles/etc/bashrc_help ~/.bashrc_help
ln -s ~/Dropbox/dotfiles/etc/bashrc_app_specific ~/.bashrc_app_specific
ln -s ~/Dropbox/dotfiles/etc/bashrc_host_aliases ~/.bashrc_host_aliases
ln -s ~/Dropbox/dotfiles/etc/bashrc_coverago ~/.bashrc_coverago

#ln -s ~/Dropbox/dotfiles/etc/bashrc_deploy ~/.bashrc_deploy
ln -s ~/Dropbox/dotfiles/etc/railsrc ~/.railsrc
#ln -s ~/Dropbox/dotfiles/etc/bashrc_gilt ~/.bashrc_gilt

# vim
rm ~/.vimrc
rm ~/.gvimrc
rm ~/.vim

ln -s ~/Dropbox/dotfiles/etc/vim/vimrc ~/.vimrc
ln -s ~/Dropbox/dotfiles/etc/vim/gvimrc ~/.gvimrc
ln -s ~/Dropbox/dotfiles/etc/vim ~/.vim

# netbeans
#rm ~/.netbeans/6.0/config
#ln -s ~/Dropbox/dotfiles/etc/netbeans/6.0/config ~/.netbeans/6.0/config

# subversion
rm ~/.subversion
ln -s ~/Dropbox/dotfiles/etc/subversion ~/.subversion

# autotest
rm ~/.autotest
ln -s ~/Dropbox/dotfiles/etc/autotest ~/.autotest

# irb
rm ~/.irbrc
ln -s ~/Dropbox/dotfiles/etc/irbrc ~/.irbrc

# git
rm ~/.gitconfig
rm ~/.gitignore
rm ~/.gitattributes
ln -s ~/Dropbox/dotfiles/etc/gitconfig ~/.gitconfig
ln -s ~/Dropbox/dotfiles/etc/gitignore ~/.gitignore
ln -s ~/Dropbox/dotfiles/etc/gitattributes ~/.gitattributes

source ~/.bash_profile
